[Mysql]
Host = "mysql"
Port = "3306"
Username = "root"
Password = "abcd1234"
Database = "rss"

[Redis]
Host = "redis"
Port = "6379"
Password = ""

[Http]
Port = "10002"

[Proxy]
# Host = "47.117.165.47"
Host = "192.168.1.100"
Port = "8123"
