version: '3'
services:
  rss_frontend:
    image: docker12345rekcod/rss_frontend:latest
    restart: always
    depends_on:
      - rss_backend
    ports:
      - "10005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rss_backend:
    image: docker12345rekcod/rss_backend:latest
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - "./config.toml:/app/config.toml"

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./rss.sql:/docker-entrypoint-initdb.d/rss.sql

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mysql_data: null
  redis_data: null
