name: workflow
on: [push]
jobs:
  build-backend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker12345rekcod/rss_backend
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: backend

  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker12345rekcod/rss_frontend
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend
  
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - build-frontend
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: |
            --location --request POST 'http://aliyun:60010/api/execute' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "key": "xx",
                "command": "cd /root/Documents/github/new_rss_reader/deploy && docker-compose pull && docker-compose up -d"
            }'
    
  