name: workflow
on: [push]
jobs:
  build-backend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker12345rekcod/rss_backend
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: backend

  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker12345rekcod/rss_frontend
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend
  
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-backend-image
      - build-frontend-image
    steps:
      - uses: actions/checkout@master
      - name: curl
        uses: enflo/curl-action@master
        with:
          curl: >
            --location --request POST 'http://47.117.165.47:60010/api/execute'  
            --header 'Content-Type: application/json'  
            --data-raw '{ "key": "xx", "command": "cd /root/Documents/github/new_rss_reader/deploy && docker-compose pull && docker-compose up -d" }'
    
  